apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homedydns.fullname" . }}-aws
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  AWS_ACCESS_KEY_ID: {{ b64enc .Values.aws.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ b64enc .Values.aws.secretKeyId }}
  AWS_DEFAULT_REGION: {{ b64enc .Values.aws.region }}